### ISSUE TITLE
github "About" link update

### ISSUE THREAD

**Issue by lue-bird** [erlandsona/elm-accessors#4]
<http://package.elm-lang.org/packages/bChiquet/elm-accessors/latest> → <https://package.elm-lang.org/packages/erlandsona/elm-accessors/latest/>
![image](https://user-images.githubusercontent.com/81869893/171486953-b26487fc-9815-4d2e-a347-aee5072c067f.png)

**Comment by erlandsona** [comment]
Done 👌
